// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHCJB5wyZ8d9l-VuvDs7ViSb1_lvL640M',
    appId: '1:497319698545:web:76635d5749c15c66e33bd0',
    messagingSenderId: '497319698545',
    projectId: 'aistudycompanion-350c6',
    authDomain: 'aistudycompanion-350c6.firebaseapp.com',
    storageBucket: 'aistudycompanion-350c6.firebasestorage.app',
    measurementId: 'G-MF35C5NKF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzYdYD1Eqnr276GwW-HTO0QmL0VLW6FqU',
    appId: '1:497319698545:android:9e4dcead28bff6e2e33bd0',
    messagingSenderId: '497319698545',
    projectId: 'aistudycompanion-350c6',
    storageBucket: 'aistudycompanion-350c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM2EcIbzErxFAsOI0w8h43wt8Ifw_khi8',
    appId: '1:497319698545:ios:ff7380f22a166c61e33bd0',
    messagingSenderId: '497319698545',
    projectId: 'aistudycompanion-350c6',
    storageBucket: 'aistudycompanion-350c6.firebasestorage.app',
    iosBundleId: 'com.example.aiStudyCompanionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM2EcIbzErxFAsOI0w8h43wt8Ifw_khi8',
    appId: '1:497319698545:ios:ff7380f22a166c61e33bd0',
    messagingSenderId: '497319698545',
    projectId: 'aistudycompanion-350c6',
    storageBucket: 'aistudycompanion-350c6.firebasestorage.app',
    iosBundleId: 'com.example.aiStudyCompanionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHCJB5wyZ8d9l-VuvDs7ViSb1_lvL640M',
    appId: '1:497319698545:web:9545b0240390d591e33bd0',
    messagingSenderId: '497319698545',
    projectId: 'aistudycompanion-350c6',
    authDomain: 'aistudycompanion-350c6.firebaseapp.com',
    storageBucket: 'aistudycompanion-350c6.firebasestorage.app',
    measurementId: 'G-QWLDS8GG0G',
  );

}